version: 2.1
jobs:
  aws-utils:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout
      - run:
          name: Check for existing cluster
          command: |
            apt update && apt -y install curl unzip wget
            # Install awscli
            wget -q https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
            sudo unzip awscli-exe-linux-x86_64.zip
            sudo ./aws/install
            # Install eksctl
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            # Install kubectl
            wget https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
            sudo chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin
            # Check for existing cluster
            cluster=$(aws eks list-clusters --output text | awk '{print $2}')

workflows:
  aws-utils-install:
    jobs:
      - aws-utils:
          context: aws
